# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OGR_DXF2SHP
                                 A QGIS plugin
 load and process DXF file and output it as Shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-06
        copyright            : (C) 2021 by Shijin (Kevin) Yang
        email                : kevinsjy997@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OGR_DXF2SHP class from file OGR_DXF2SHP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ogr_dxf2shp import OGR_DXF2SHP
    return OGR_DXF2SHP(iface)
